#pragma once
#include <pebble.h>
#define ACCURACY_QUARTER    0
#define ACCURACY_HALF       1
#define ACCURACY_HOUR       2
#define ACCURACY_HALF_DAY   3
#define ACCURACY_DAY_NIGHT  4
#define ACCURACY_PERIOD     5

static const uint32_t FARSI_QUARTER[12][4] = {
  { RESOURCE_ID_IMG_EXACT_0, RESOURCE_ID_IMG_QUARTER_0, RESOURCE_ID_IMG_HALF_0, RESOURCE_ID_IMG_TONEXT_0 },
  { RESOURCE_ID_IMG_EXACT_1, RESOURCE_ID_IMG_QUARTER_1, RESOURCE_ID_IMG_HALF_1, RESOURCE_ID_IMG_TONEXT_1 },
  { RESOURCE_ID_IMG_EXACT_2, RESOURCE_ID_IMG_QUARTER_2, RESOURCE_ID_IMG_HALF_2, RESOURCE_ID_IMG_TONEXT_2 },
  { RESOURCE_ID_IMG_EXACT_3, RESOURCE_ID_IMG_QUARTER_3, RESOURCE_ID_IMG_HALF_3, RESOURCE_ID_IMG_TONEXT_3 },
  { RESOURCE_ID_IMG_EXACT_4, RESOURCE_ID_IMG_QUARTER_4, RESOURCE_ID_IMG_HALF_4, RESOURCE_ID_IMG_TONEXT_4 },
  { RESOURCE_ID_IMG_EXACT_5, RESOURCE_ID_IMG_QUARTER_5, RESOURCE_ID_IMG_HALF_5, RESOURCE_ID_IMG_TONEXT_5 },
  { RESOURCE_ID_IMG_EXACT_6, RESOURCE_ID_IMG_QUARTER_6, RESOURCE_ID_IMG_HALF_6, RESOURCE_ID_IMG_TONEXT_6 },
  { RESOURCE_ID_IMG_EXACT_7, RESOURCE_ID_IMG_QUARTER_7, RESOURCE_ID_IMG_HALF_7, RESOURCE_ID_IMG_TONEXT_7 },
  { RESOURCE_ID_IMG_EXACT_8, RESOURCE_ID_IMG_QUARTER_8, RESOURCE_ID_IMG_HALF_8, RESOURCE_ID_IMG_TONEXT_8 },
  { RESOURCE_ID_IMG_EXACT_9, RESOURCE_ID_IMG_QUARTER_9, RESOURCE_ID_IMG_HALF_9, RESOURCE_ID_IMG_TONEXT_9 },
  { RESOURCE_ID_IMG_EXACT_10, RESOURCE_ID_IMG_QUARTER_10, RESOURCE_ID_IMG_HALF_10, RESOURCE_ID_IMG_TONEXT_10 },
  { RESOURCE_ID_IMG_EXACT_11, RESOURCE_ID_IMG_QUARTER_11, RESOURCE_ID_IMG_HALF_11, RESOURCE_ID_IMG_TONEXT_11 },
};
static const uint32_t FARSI_HALF[12][2] = {
  { RESOURCE_ID_IMG_EXACT_0, RESOURCE_ID_IMG_HALF_0 },
  { RESOURCE_ID_IMG_EXACT_1, RESOURCE_ID_IMG_HALF_1 },
  { RESOURCE_ID_IMG_EXACT_2, RESOURCE_ID_IMG_HALF_2 },
  { RESOURCE_ID_IMG_EXACT_3, RESOURCE_ID_IMG_HALF_3 },
  { RESOURCE_ID_IMG_EXACT_4, RESOURCE_ID_IMG_HALF_4 },
  { RESOURCE_ID_IMG_EXACT_5, RESOURCE_ID_IMG_HALF_5 },
  { RESOURCE_ID_IMG_EXACT_6, RESOURCE_ID_IMG_HALF_6 },
  { RESOURCE_ID_IMG_EXACT_7, RESOURCE_ID_IMG_HALF_7 },
  { RESOURCE_ID_IMG_EXACT_8, RESOURCE_ID_IMG_HALF_8 },
  { RESOURCE_ID_IMG_EXACT_9, RESOURCE_ID_IMG_HALF_9 },
  { RESOURCE_ID_IMG_EXACT_10, RESOURCE_ID_IMG_HALF_10 },
  { RESOURCE_ID_IMG_EXACT_11, RESOURCE_ID_IMG_HALF_11 },
};
static const uint32_t FARSI_HOUR[12] = {
  RESOURCE_ID_IMG_EXACT_0,
  RESOURCE_ID_IMG_EXACT_1,
  RESOURCE_ID_IMG_EXACT_2,
  RESOURCE_ID_IMG_EXACT_3,
  RESOURCE_ID_IMG_EXACT_4,
  RESOURCE_ID_IMG_EXACT_5,
  RESOURCE_ID_IMG_EXACT_6,
  RESOURCE_ID_IMG_EXACT_7,
  RESOURCE_ID_IMG_EXACT_8,
  RESOURCE_ID_IMG_EXACT_9,
  RESOURCE_ID_IMG_EXACT_10,
  RESOURCE_ID_IMG_EXACT_11,
};
static const uint32_t FARSI_HALF_DAY[2] = {
  RESOURCE_ID_IMG_HALFDAY_0,
  RESOURCE_ID_IMG_HALFDAY_1,
};
static const uint32_t FARSI_DAY_NIGHT[2] = {
  RESOURCE_ID_IMG_DAYNIGHT_0,
  RESOURCE_ID_IMG_DAYNIGHT_1,
};
static const uint32_t FARSI_PERIOD[5] = {
  RESOURCE_ID_IMG_PERIOD_0,
  RESOURCE_ID_IMG_PERIOD_1,
  RESOURCE_ID_IMG_PERIOD_2,
  RESOURCE_ID_IMG_PERIOD_3,
  RESOURCE_ID_IMG_PERIOD_4,
};